version: '3'
services:
  ru-database:
    image: mongo
    container_name: ru-db
    environment:
      MONGO_INITDB_DATABASE: app-database
      MONGO_INITDB_ROOT_USERNAME: ru-app
      MONGO_INITDB_ROOT_PASSWORD: app-password
    ports:
      - "27017:27017"

  ru-app:
    image: ru-app
    container_name: ru-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - config/.env
    volumes:
      - "./:/app"
    ports:
      - "8000:8000"

